apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
# renovate: type=remote-file
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/install.yaml
